[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/152P8Nuk-dlb7S_EYrodxXzAsqZNBXJ5eV2mdzXKRVn4"
type = "service_account"
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
token_uri = "https://oauth2.googleapis.com/token"
ANTHROPIC_API_KEY = "sk-ant-api03-..."
